<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\QuantityMeasurementModel\QuantityMeasurementModel.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- NEW: ADO.NET provider for SQL Server -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />
  </ItemGroup>
   <!-- NEW: EF Core base package (for DbContext and ModelBuilder) -->
  <ItemGroup>
    <!-- EF Core base -->
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <!-- EF Core relational extensions (ToTable, etc.) -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.0" />
    <!-- EF Core SQL Server provider (needed for UseSqlOutputClause) -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <!-- Redis client -->
    <PackageReference Include="StackExchange.Redis" Version="2.6.122" />
  </ItemGroup>


</Project>